#!/usr/bin/env python3
"""
Demo Runner — drives the Boundary MCP + RDP Computer Use MCP servers
to execute the full 6-phase demo end-to-end.

Usage:
    export WINDOWS_PASSWORD="your-windows-password"
    python3 scripts/run-demo.py

Requires:
    - .mcp.json with correct paths and tokens (generated by demo.sh --setup)
    - Windows host reachable via Boundary
    - System packages: xfreerdp3, xdotool, Xvfb, import, scrot
"""

import json
import subprocess
import sys
import os
import time
import base64
import hashlib
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.parent
MCP_CONFIG_PATH = SCRIPT_DIR / ".mcp.json"

WIDTH = 1280
HEIGHT = 720


class McpClient:
    """Minimal MCP stdio client."""

    def __init__(self, name, command, args=None, env=None):
        self.name = name
        self.proc = None
        self._next_id = 1
        full_env = os.environ.copy()
        if env:
            full_env.update(env)
        cmd = [command]
        if args:
            cmd.extend(args)
        self.proc = subprocess.Popen(
            cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, env=full_env,
        )

    def _send(self, method, params=None):
        msg_id = self._next_id
        self._next_id += 1
        req = {"jsonrpc": "2.0", "id": msg_id, "method": method}
        if params is not None:
            req["params"] = params
        data = json.dumps(req) + "\n"
        if self.proc.stdin is None:
            raise RuntimeError(f"[{self.name}] stdin is closed")
        self.proc.stdin.write(data.encode())
        self.proc.stdin.flush()
        while True:
            line = self.proc.stdout.readline()
            if not line:
                raise RuntimeError(f"[{self.name}] Process closed stdout")
            line = line.strip()
            if not line:
                continue
            try:
                resp = json.loads(line)
            except json.JSONDecodeError:
                continue
            if resp.get("id") == msg_id:
                if "error" in resp:
                    return resp["error"]
                return resp.get("result")

    def initialize(self):
        result = self._send("initialize", {
            "protocolVersion": "2024-11-05", "capabilities": {},
            "clientInfo": {"name": "demo-runner", "version": "2.0.0"},
        })
        msg = {"jsonrpc": "2.0", "method": "notifications/initialized"}
        data = json.dumps(msg) + "\n"
        if self.proc.stdin is not None:
            self.proc.stdin.write(data.encode())
            self.proc.stdin.flush()
        return result

    def call_tool(self, tool_name, arguments=None):
        params = {"name": tool_name}
        if arguments:
            params["arguments"] = arguments
        result = self._send("tools/call", params)
        if result and isinstance(result, dict) and "content" in result:
            for content in result["content"]:
                if content.get("type") == "text":
                    try:
                        return json.loads(content["text"])
                    except json.JSONDecodeError:
                        return {"raw": content["text"]}
        return result

    def close(self):
        if self.proc:
            try:
                self.proc.stdin.close()
            except:
                pass
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except:
                self.proc.kill()


def load_mcp_config():
    with open(MCP_CONFIG_PATH) as f:
        config = json.load(f)
    return config["mcpServers"]


def screenshot(rdp_mcp, phase, step, label=""):
    result = rdp_mcp.call_tool("rdp_screenshot")
    if isinstance(result, dict) and "screenshot_path" in result:
        src = result["screenshot_path"]
        screenshot_dir = "/tmp/rdp-screenshots"
        os.makedirs(screenshot_dir, exist_ok=True)
        dst = os.path.join(screenshot_dir, f"phase{phase}_step{step}.png")
        if os.path.exists(src):
            os.system(f"cp {src} {dst}")
        elif "screenshot_base64" in result:
            img_data = base64.b64decode(result["screenshot_base64"])
            with open(dst, "wb") as f:
                f.write(img_data)
        size = os.path.getsize(dst) if os.path.exists(dst) else 0
        w = result.get("width", "?")
        h = result.get("height", "?")
        print(f"  📸 [{label}] {dst} ({size} bytes, {w}x{h})")
        return dst
    print(f"  ⚠️  Screenshot failed: {result}")
    return None


def type_and_enter(rdp_mcp, text, wait=2):
    rdp_mcp.call_tool("rdp_type", {"text": text})
    time.sleep(0.5)
    rdp_mcp.call_tool("rdp_key", {"keys": "Return"})
    time.sleep(wait)


def log(phase, step, msg):
    print(f"\n{'='*60}")
    print(f"  Phase {phase}, Step {step}: {msg}")
    print(f"{'='*60}")


def kill_stale_processes():
    os.system("pkill -f 'Xvfb.*:100' 2>/dev/null || true")
    os.system("pkill -f xfreerdp3 2>/dev/null || true")
    os.system("pkill -f 'boundary connect' 2>/dev/null || true")
    os.system("rm -f /tmp/.X100-lock /tmp/.X11-unix/X100 2>/dev/null || true")
    time.sleep(2)


def main():
    print("=" * 60)
    print("  Boundary MCP RDP Computer Use Demo — Full 6-Phase Run (v2)")
    print("=" * 60)

    print("\nCleaning up stale processes...")
    kill_stale_processes()

    servers = load_mcp_config()
    boundary_cfg = servers["boundary"]
    rdp_cfg = servers["rdp-computer-use"]

    print("Starting Boundary MCP server...")
    boundary_mcp = McpClient("boundary", boundary_cfg["command"], env=boundary_cfg.get("env"))
    boundary_mcp.initialize()
    print("  ✅ Boundary MCP server started")

    print("Starting RDP Computer Use MCP server...")
    rdp_mcp = McpClient("rdp", rdp_cfg["command"], args=rdp_cfg.get("args"), env=rdp_cfg.get("env"))
    rdp_mcp.initialize()
    print("  ✅ RDP Computer Use MCP server started")

    windows_password = os.environ.get("WINDOWS_PASSWORD", "")
    if not windows_password:
        print("❌ WINDOWS_PASSWORD environment variable is required")
        print("   Set it to the Windows host's Administrator password")
        sys.exit(1)
    windows_username = os.environ.get("WINDOWS_USERNAME", "Administrator")
    boundary_token = rdp_cfg.get("env", {}).get("BOUNDARY_TOKEN", "")

    try:
        # Phase 1: Discover and Connect
        log(1, 1, "List targets to find windows-rdp")
        targets_result = boundary_mcp.call_tool("list_targets")
        target_id = None
        if isinstance(targets_result, dict):
            items = targets_result.get("targets", targets_result.get("items", []))
            for t in items:
                if "rdp" in t.get("name", "").lower():
                    target_id = t["id"]
                    print(f"  ✅ Found target: {t['name']} ({target_id})")
                    break
        if not target_id:
            demo_state = SCRIPT_DIR / ".demo-state"
            if demo_state.exists():
                for line in demo_state.read_text().splitlines():
                    if line.startswith("TARGET_ID="):
                        target_id = line.split("=", 1)[1]
                        print(f"  ⚠️  Using target from .demo-state: {target_id}")
                        break
        if not target_id:
            print("  ❌ No target found!")
            sys.exit(1)

        log(1, 2, f"Connect RDP (target: {target_id})")
        connect_result = rdp_mcp.call_tool("connect_rdp", {
            "target_id": target_id, "username": windows_username,
            "password": windows_password, "boundary_token": boundary_token,
            "width": WIDTH, "height": HEIGHT,
        })
        if isinstance(connect_result, dict) and connect_result.get("status") == "connected":
            print(f"  ✅ Connected! Proxy: {connect_result.get('proxy','?')}")
        else:
            print(f"  ❌ Connection failed: {connect_result}")
            sys.exit(1)

        log(1, 3, "Initial screenshot")
        screenshot(rdp_mcp, 1, 3, "Initial desktop")

        # Phase 2: Set Up IIS
        log(2, 1, "Open PowerShell")
        rdp_mcp.call_tool("rdp_key", {"keys": "super"})
        time.sleep(2)
        screenshot(rdp_mcp, 2, 1, "Start menu open")
        rdp_mcp.call_tool("rdp_type", {"text": "powershell"})
        time.sleep(1)
        screenshot(rdp_mcp, 2, 1, "After typing powershell")
        rdp_mcp.call_tool("rdp_key", {"keys": "Return"})
        time.sleep(4)
        screenshot(rdp_mcp, 2, 1, "PowerShell open")

        # Click on PowerShell window to ensure focus
        rdp_mcp.call_tool("rdp_click", {"x": 640, "y": 400})
        time.sleep(1)

        log(2, 2, "Install IIS Web Server role")
        type_and_enter(rdp_mcp, "Install-WindowsFeature -Name Web-Server", wait=30)
        screenshot(rdp_mcp, 2, 2, "IIS installation result")
        time.sleep(10)
        screenshot(rdp_mcp, 2, 2, "IIS installation final")

        log(2, 3, "Create hello.html")
        html = '<html><body><h1>Hello World from Boundary!</h1><p>Deployed by AI agent via RDP through HashiCorp Boundary.</p></body></html>'
        type_and_enter(rdp_mcp, f'Set-Content -Path "C:\\inetpub\\wwwroot\\hello.html" -Value "{html}" -Force', wait=2)
        screenshot(rdp_mcp, 2, 3, "hello.html created")

        log(2, 4, "Verify IIS serving the page")
        type_and_enter(rdp_mcp, 'C:\\Windows\\System32\\curl.exe -s http://localhost/hello.html', wait=3)
        screenshot(rdp_mcp, 2, 4, "curl hello.html")

        type_and_enter(rdp_mcp, 'C:\\Windows\\System32\\curl.exe -s -o NUL -w "HTTP_STATUS:%{http_code}" http://localhost/hello.html', wait=2)
        screenshot(rdp_mcp, 2, 4, "HTTP status check")

        # Phase 3: Create a New Windows User
        log(3, 1, "Create local user 'demo-user'")
        type_and_enter(rdp_mcp, 'New-LocalUser -Name "demo-user" -Description "Demo user created by AI agent" -NoPassword', wait=3)
        screenshot(rdp_mcp, 3, 1, "User creation")

        log(3, 2, "Add user to Users group")
        type_and_enter(rdp_mcp, 'Add-LocalGroupMember -Group "Users" -Member "demo-user"', wait=2)
        screenshot(rdp_mcp, 3, 2, "Added to group")

        log(3, 3, "Verify user exists")
        type_and_enter(rdp_mcp, 'Get-LocalUser -Name "demo-user" | Select-Object Name, Enabled, Description', wait=2)
        screenshot(rdp_mcp, 3, 3, "User details")

        # Phase 4: Open the Web Page in a Browser
        log(4, 1, "Open Edge browser")
        type_and_enter(rdp_mcp, 'Start-Process msedge "http://localhost/hello.html"', wait=6)
        screenshot(rdp_mcp, 4, 1, "Edge browser with hello page")

        # Phase 5: Edit the Page and Verify the Update
        log(5, 1, "Switch back to PowerShell")
        rdp_mcp.call_tool("rdp_key", {"keys": "alt+Tab"})
        time.sleep(2)
        screenshot(rdp_mcp, 5, 1, "Back to PowerShell")

        log(5, 2, "Edit hello.html with updated content")
        updated = '<html><body><h1>Hello World from Boundary - UPDATED!</h1><p>This page was edited by an AI agent via RDP.</p><p>User demo-user was created.</p></body></html>'
        type_and_enter(rdp_mcp, f'Set-Content -Path "C:\\inetpub\\wwwroot\\hello.html" -Value "{updated}" -Force', wait=2)
        screenshot(rdp_mcp, 5, 2, "Page edited")

        log(5, 3, "Switch to Edge and refresh")
        rdp_mcp.call_tool("rdp_key", {"keys": "alt+Tab"})
        time.sleep(2)
        rdp_mcp.call_tool("rdp_key", {"keys": "F5"})
        time.sleep(4)
        screenshot(rdp_mcp, 5, 3, "Browser refreshed")

        log(5, 4, "Confirm update with curl")
        rdp_mcp.call_tool("rdp_key", {"keys": "alt+Tab"})
        time.sleep(2)
        type_and_enter(rdp_mcp, 'C:\\Windows\\System32\\curl.exe -s http://localhost/hello.html', wait=2)
        screenshot(rdp_mcp, 5, 4, "curl updated content")

        # Phase 6: Disconnect
        log(6, 1, "Disconnect RDP session")
        result = rdp_mcp.call_tool("rdp_disconnect")
        print(f"  {json.dumps(result, indent=2) if isinstance(result, dict) else result}")

        print("\n" + "=" * 60)
        print("  ✅ Demo completed!")
        print("=" * 60)
        print(f"  Screenshots: /tmp/rdp-screenshots/phase*.png")
        print(f"  Phases: 1-Connect ✅  2-IIS ✅  3-User ✅  4-Browser ✅  5-Edit ✅  6-Disconnect ✅")

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        try:
            rdp_mcp.call_tool("rdp_disconnect")
        except:
            pass
        sys.exit(1)
    finally:
        boundary_mcp.close()
        rdp_mcp.close()


if __name__ == "__main__":
    main()